# Generated by Django 3.0.5 on 2020-04-20 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('krishiKarma', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmer',
            name='Map',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='farmer',
            name='budget',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='farmer',
            name='fundRaisedTillNow',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='farmer',
            name='loanRaised',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='farmer',
            name='loanRequired',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='farmer',
            name='phValue',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='farmer',
            name='plotno',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='farmer',
            name='soil',
            field=models.IntegerField(blank=True),
        ),
    ]
