# Generated by Django 3.0.5 on 2020-04-20 14:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('krishiKarma', '0002_auto_20200420_1410'),
    ]

    operations = [
        migrations.CreateModel(
            name='Soil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='district',
            name='crops',
            field=models.ManyToManyField(blank=True, related_name='districts', to='krishiKarma.Crop'),
        ),
        migrations.AlterField(
            model_name='district',
            name='state',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='districts', to='krishiKarma.State'),
        ),
        migrations.AlterField(
            model_name='farmer',
            name='soil',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='farmers', to='krishiKarma.Soil'),
        ),
    ]
