# Generated by Django 3.0.5 on 2020-04-25 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('krishiKarma', '0004_auto_20200425_2217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmer',
            name='phValue',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=5),
        ),
    ]
