# Generated by Django 3.0.5 on 2020-04-26 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('krishiKarma', '0005_auto_20200425_2225'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmer',
            name='plotSize',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
