# Generated by Django 3.0.5 on 2020-04-26 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('krishiKarma', '0006_farmer_plotsize'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmer',
            name='plotSize',
            field=models.IntegerField(blank=True, default=2),
            preserve_default=False,
        ),
    ]
